1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?


1.Write a Python Program to Add Two Matrices?

In [29]:
import numpy as np
def matrixs(mat1,mat2):
    return mat1+mat2
mat1=np.array([[1,2],[1,2]])#matrix1
mat2=np.array([[3,2],[4,5]])#matrix2
print("the matrix 1 and 2 befor adding")
print(mat1)
print(mat2)
print("after adding above matrix1 and matrix2 is:")
matrixs(mat1,mat2)

the matrix 1 and 2 befor adding
[[1 2]
 [1 2]]
[[3 2]
 [4 5]]
after adding matrix1 and matrix2 is:


array([[4, 4],
       [5, 7]])

2.Write a Python Program to Multiply Two Matrices?

In [30]:
import numpy as np
def matrixs(mat1,mat2):
    return mat1*mat2
mat1=np.array([[1,2],[1,2]])#matrix1
mat2=np.array([[3,2],[4,5]])#matrix2
print(mat1)
print(mat2)
print("after adding matrix1 and matrix2 is")
matrixs(mat1,mat2)

[[1 2]
 [1 2]]
[[3 2]
 [4 5]]
after adding matrix1 and matrix2 is


array([[ 3,  4],
       [ 4, 10]])

3.Write a Python Program to Transpose a Matrix?

In [35]:
import numpy as np
mat1=np.array([[1,2],[6,1]])#matrix1
print("Before transpoing the given matrix")
print(mat1)
print("after transpose")
c=mat1.T
print(c)


Before transpoing the given matrix
[[1 2]
 [6 1]]
after transpose
[[1 6]
 [2 1]]


4.Write a Python Program to Sort Words in Alphabetic Order

In [54]:
c=input("enter a string to sort it")
d=c.split()
d.sort()
for i in d:
    print(i)

enter a string to sort itb c a
a
b
c


5. a Python Program to Remove Punctuation From a String?

In [2]:
c='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
d=input("enter a string")
e=""
for i in d:
    if i not in c:
        e=e+i
print(e)
        

enter a stringabc()(<>
abc
